import unittest
from _typeshed import Incomplete
from mumulib.mumutypes import BadRequestResponse as BadRequestResponse, CreatedResponse as CreatedResponse, HTTPResponse as HTTPResponse, MethodNotAllowedResponse as MethodNotAllowedResponse, NotFoundResponse as NotFoundResponse, SeeOtherResponse as SeeOtherResponse, SpecialResponse as SpecialResponse

cov: Incomplete

class TestSpecialResponse(unittest.TestCase):
    def test_init_without_writer(self) -> None: ...
    def test_init_with_writer(self): ...
    def test_is_exception(self) -> None: ...

class TestHTTPResponse(unittest.TestCase):
    def test_init(self) -> None: ...
    def test_custom_status_code(self) -> None: ...

class TestBadRequestResponse(unittest.TestCase):
    def test_init(self) -> None: ...
    def test_inherits_from_http_response(self) -> None: ...

class TestNotFoundResponse(unittest.TestCase):
    def test_init(self) -> None: ...
    def test_inherits_from_http_response(self) -> None: ...

class TestMethodNotAllowedResponse(unittest.TestCase):
    def test_init(self) -> None: ...
    def test_inherits_from_http_response(self) -> None: ...

class TestCreatedResponse(unittest.TestCase):
    def test_init(self) -> None: ...
    def test_inherits_from_http_response(self) -> None: ...

class TestSeeOtherResponse(unittest.TestCase):
    def test_init(self) -> None: ...
    def test_inherits_from_special_response(self) -> None: ...
    def test_unicode_redirect_url(self) -> None: ...
