import unittest
from _typeshed import Incomplete
from mumulib import mumutypes as mumutypes
from mumulib.producers import add_producer as add_producer, custom_serializer as custom_serializer, produce as produce, produce_file as produce_file, produce_json as produce_json

cov: Incomplete

class TestCustomSerializer(unittest.TestCase):
    def test_mapping_proxy_type(self) -> None: ...
    def test_non_mapping_proxy_type(self) -> None: ...

class TestAddProducer(unittest.TestCase):
    async def async_test_add_producer_default_mime(self) -> None: ...
    def test_add_producer_default_mime(self) -> None: ...
    async def async_test_add_producer_custom_mime(self) -> None: ...
    def test_add_producer_custom_mime(self) -> None: ...

class TestProduceWithAdapters(unittest.TestCase):
    data: Incomplete
    async def async_test_adapter_mechanism(self) -> None: ...
    def test_adapter_mechanism(self) -> None: ...
    async def async_test_adapter_fallback(self): ...
    def test_adapter_fallback(self) -> None: ...
    async def async_test_json_adapter(self) -> None: ...
    def test_json_adapter(self) -> None: ...

class TestProduceWithFunctions(unittest.TestCase):
    async def async_test_function_producer(self) -> None: ...
    def test_function_producer(self) -> None: ...
    async def async_test_function_receives_itself(self) -> None: ...
    def test_function_receives_itself(self) -> None: ...

class TestProduceJson(unittest.TestCase):
    async def async_test_produce_json_dict(self) -> None: ...
    def test_produce_json_dict(self) -> None: ...
    async def async_test_produce_json_with_mapping_proxy(self) -> None: ...
    def test_produce_json_with_mapping_proxy(self) -> None: ...

class TestProduceFile(unittest.TestCase):
    async def async_test_produce_text_file(self) -> None: ...
    def test_produce_text_file(self) -> None: ...
    async def async_test_produce_file_content_type(self) -> None: ...
    def test_produce_file_content_type(self) -> None: ...
    async def async_test_produce_file_with_unknown_type(self) -> None: ...
    def test_produce_file_with_unknown_type(self) -> None: ...
    async def async_test_produce_ttf_file(self) -> None: ...
    def test_produce_ttf_file(self) -> None: ...
