import unittest
from _typeshed import Incomplete
from mumulib.server import DEFAULT_MAX_BODY_SIZE as DEFAULT_MAX_BODY_SIZE, consumers_app as consumers_app, parse_json as parse_json, parse_multipart as parse_multipart, parse_urlencoded as parse_urlencoded

cov: Incomplete

class TestParseJson(unittest.TestCase):
    async def async_test_parse_json_basic(self): ...
    def test_parse_json_basic(self) -> None: ...
    async def async_test_parse_json_empty_body(self): ...
    def test_parse_json_empty_body(self) -> None: ...
    async def async_test_parse_json_chunked(self): ...
    def test_parse_json_chunked(self) -> None: ...
    async def async_test_parse_json_size_limit_exceeded(self): ...
    def test_parse_json_size_limit_exceeded(self) -> None: ...

class TestParseUrlencoded(unittest.TestCase):
    async def async_test_parse_urlencoded_basic(self): ...
    def test_parse_urlencoded_basic(self) -> None: ...
    async def async_test_parse_urlencoded_array_syntax(self): ...
    def test_parse_urlencoded_array_syntax(self) -> None: ...
    async def async_test_parse_urlencoded_empty_body(self): ...
    def test_parse_urlencoded_empty_body(self) -> None: ...
    async def async_test_parse_urlencoded_chunked(self): ...
    def test_parse_urlencoded_chunked(self) -> None: ...
    async def async_test_parse_urlencoded_size_limit(self): ...
    def test_parse_urlencoded_size_limit(self) -> None: ...

class TestConsumersAppLifespan(unittest.TestCase):
    async def async_test_lifespan_startup_shutdown(self): ...
    def test_lifespan_startup_shutdown(self) -> None: ...

class TestConsumersAppRouting(unittest.TestCase):
    async def async_test_json_content_type_header(self): ...
    def test_json_content_type_header(self) -> None: ...
    async def async_test_json_path_extension(self): ...
    def test_json_path_extension(self) -> None: ...
    async def async_test_html_path_extension(self): ...
    def test_html_path_extension(self) -> None: ...

class TestParseMultipart(unittest.TestCase):
    async def async_test_parse_multipart_basic(self): ...
    def test_parse_multipart_basic(self) -> None: ...
    async def async_test_parse_multipart_with_file(self): ...
    def test_parse_multipart_with_file(self) -> None: ...
    async def async_test_parse_multipart_multiple_chunks(self): ...
    def test_parse_multipart_multiple_chunks(self) -> None: ...
    async def async_test_parse_multipart_malformed_part(self): ...
    def test_parse_multipart_malformed_part(self) -> None: ...

class TestBytesResultHandling(unittest.TestCase):
    async def async_test_bytes_result(self): ...
    def test_bytes_result(self) -> None: ...

class TestExceptionHandling(unittest.TestCase):
    async def async_test_exception_during_consume(self): ...
    def test_exception_during_consume(self) -> None: ...
    async def async_test_special_response_result(self): ...
    def test_special_response_result(self) -> None: ...
    async def async_test_special_response_with_non_string_leaf(self): ...
    def test_special_response_with_non_string_leaf(self) -> None: ...
    async def async_test_special_response_exception_during_produce(self): ...
    def test_special_response_exception_during_produce(self) -> None: ...
    async def async_test_generic_exception_during_produce(self): ...
    def test_generic_exception_during_produce(self) -> None: ...
    async def async_test_special_response_exception_after_first_chunk(self): ...
    def test_special_response_exception_after_first_chunk(self) -> None: ...
    async def async_test_generic_exception_after_first_chunk(self): ...
    def test_generic_exception_after_first_chunk(self) -> None: ...

class TestSpecialResponseWithWriter(unittest.TestCase):
    async def async_test_special_response_with_writer(self): ...
    def test_special_response_with_writer(self) -> None: ...
    async def async_test_special_response_without_writer(self): ...
    def test_special_response_without_writer(self) -> None: ...

class TestUnknownContentType(unittest.TestCase):
    async def async_test_unknown_content_type(self): ...
    def test_unknown_content_type(self) -> None: ...

class TestRequestSizeLimits(unittest.TestCase):
    async def async_test_json_size_limit_exceeded(self): ...
    def test_json_size_limit_exceeded(self) -> None: ...
    async def async_test_urlencoded_size_limit_exceeded(self): ...
    def test_urlencoded_size_limit_exceeded(self) -> None: ...
    async def async_test_multipart_size_limit_exceeded(self): ...
    def test_multipart_size_limit_exceeded(self) -> None: ...

class TestEventSource(unittest.TestCase):
    async def async_test_eventsource_streaming(self): ...
    def test_eventsource_streaming(self) -> None: ...
    async def async_test_eventsource_client_disconnect(self): ...
    def test_eventsource_client_disconnect(self) -> None: ...
